on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true

      - name: Install CMU Fonts and Update Databases
        run: |
          # Install the cm-unicode package which provides the CMU fonts
          tlmgr install cm-unicode
          # Update TeX’s filename database
          mktexlsr
          # Update LuaLaTeX font cache
          luaotfload-tool --update
          # Set OSFONTDIR so that fontconfig can find the fonts
          export OSFONTDIR="$HOME/.TinyTeX/texmf-dist/fonts/opentype"
          # Update the system font cache (fontconfig)
          fc-cache -f -v

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Make sure the OSFONTDIR is available in the render environment
          OSFONTDIR: $HOME/.TinyTeX/texmf-dist/fonts/opentype
