on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true

      - name: Install CMU Serif Fonts Manually
        run: |
          # Download CMU Serif font package
          wget https://sourceforge.net/projects/cm-unicode/files/0.7.0/cmuntt.zip/download -O cmuntt.zip
          
          # Unzip the font files
          unzip cmuntt.zip -d cmun_fonts
          
          # Create a fonts directory for CMU and copy the fonts
          sudo mkdir -p /usr/share/fonts/truetype/cmun
          sudo cp cmun_fonts/*.ttf /usr/share/fonts/truetype/cmun/
          
          # Update the font cache
          sudo fc-cache -fv

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}