on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    env:
      OSFONTDIR: $HOME/.TinyTeX/texmf-dist/fonts/opentype
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true

      - name: Install CMU Fonts and Update Databases
        run: |
          tlmgr install cm-unicode
          mktexlsr
          luaotfload-tool --force
          # Update the system font cache using fc-cache
          fc-cache -f -v

      - name: "Debug: List CMU Fonts Files"
        run: |
          echo "Listing files in TinyTeX CMU directory:"
          find "$HOME/.TinyTeX/texmf-dist/fonts/opentype/public/cmun" -type f

      - name: "Debug: List Fonts via fc-list"
        run: |
          echo "Listing fonts via fc-list:"
          fc-list | grep -i "cmu"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
