on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install CMU Unicode Fonts Manually
        run: |
          sudo apt-get update
          sudo apt-get install fonts-cmu

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tinytex: true

      - name: Debug Font Files
        run: |
          ls -R files/palatino/
      
      - name: Register Custom Fonts
        run: |
          mkdir -p ~/.fonts
          cp files/palatino/*.ttf ~/.fonts/
          fc-cache -f -v
          fc-list | grep -i palatino

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}